
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author compaq
 */
public class Form extends javax.swing.JFrame {

    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JFORM = new javax.swing.JLabel();
        JNOPENDAFTARAN = new javax.swing.JLabel();
        JNAME = new javax.swing.JLabel();
        JTTL = new javax.swing.JLabel();
        JJENISKELAMIN = new javax.swing.JLabel();
        JALAMAT = new javax.swing.JLabel();
        JAGAMA = new javax.swing.JLabel();
        JKOJUR = new javax.swing.JLabel();
        JNAJUR = new javax.swing.JLabel();
        TXTNOPENDAFTARAN = new javax.swing.JTextField();
        TXTNAMA = new javax.swing.JTextField();
        TXTTTL = new javax.swing.JTextField();
        RBLK = new javax.swing.JRadioButton();
        RBPR = new javax.swing.JRadioButton();
        TXTALAMAT = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        CBKOJUR = new javax.swing.JComboBox<>();
        JJALUR = new javax.swing.JLabel();
        JSPI = new javax.swing.JLabel();
        JGELOMBANG = new javax.swing.JLabel();
        JUKT = new javax.swing.JLabel();
        JBIAYAPENDAFTARAN = new javax.swing.JLabel();
        JPERHITUNGANBIAYA = new javax.swing.JLabel();
        JTOTALBIAYA = new javax.swing.JLabel();
        RBSNMPTN = new javax.swing.JRadioButton();
        RBSBMPTN = new javax.swing.JRadioButton();
        TXTSPI = new javax.swing.JTextField();
        CBGELOMBANG = new javax.swing.JComboBox<>();
        TXTUKT = new javax.swing.JTextField();
        TXTBIAYAPENDAFTARAN = new javax.swing.JTextField();
        TXTNAJUR = new javax.swing.JTextField();
        BTNDAFTAR = new javax.swing.JButton();
        BTNKELUAR = new javax.swing.JButton();
        BTNHITUNG = new javax.swing.JButton();
        TXTTOTAL = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JFORM.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        JFORM.setText("FORM PENDAFTARAN MAHASISWA BARU");

        JNOPENDAFTARAN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JNOPENDAFTARAN.setText("No pendafataran");

        JNAME.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JNAME.setText("Nama");

        JTTL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JTTL.setText("TTL");

        JJENISKELAMIN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JJENISKELAMIN.setText("Jenis kelamin");

        JALAMAT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JALAMAT.setText("Alamat");

        JAGAMA.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JAGAMA.setText("Agama");

        JKOJUR.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JKOJUR.setText("Kode Jurusan");

        JNAJUR.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JNAJUR.setText("Nama Jurusan");

        RBLK.setText("Laki - Laki");

        RBPR.setText("Perempuan");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Islam", "kristen", "Hindu", "Budha" }));
        jComboBox1.setToolTipText("");

        CBKOJUR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "11", "12", "13", "14", "15" }));
        CBKOJUR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBKOJURActionPerformed(evt);
            }
        });

        JJALUR.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JJALUR.setText("Jalur Pendaftaran");

        JSPI.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JSPI.setText("SPI");

        JGELOMBANG.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JGELOMBANG.setText("Gelombang");

        JUKT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JUKT.setText("UKT");

        JBIAYAPENDAFTARAN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JBIAYAPENDAFTARAN.setText("Biaya Pendaftaran");

        JPERHITUNGANBIAYA.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JPERHITUNGANBIAYA.setText("Perhitungan Biaya");

        JTOTALBIAYA.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JTOTALBIAYA.setText("Total Biaya");

        RBSNMPTN.setText("SNMPTN");
        RBSNMPTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBSNMPTNActionPerformed(evt);
            }
        });

        RBSBMPTN.setText("SBMPTN");
        RBSBMPTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBSBMPTNActionPerformed(evt);
            }
        });

        CBGELOMBANG.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));
        CBGELOMBANG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBGELOMBANGActionPerformed(evt);
            }
        });

        BTNDAFTAR.setText("DAFTAR");
        BTNDAFTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNDAFTARActionPerformed(evt);
            }
        });

        BTNKELUAR.setText("KELUAR");
        BTNKELUAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNKELUARActionPerformed(evt);
            }
        });

        BTNHITUNG.setText("HITUNG");
        BTNHITUNG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNHITUNGActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BTNKELUAR)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JNOPENDAFTARAN)
                            .addComponent(JNAME)
                            .addComponent(JTTL)
                            .addComponent(JJENISKELAMIN)
                            .addComponent(JALAMAT)
                            .addComponent(JAGAMA)
                            .addComponent(JKOJUR)
                            .addComponent(JNAJUR))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(TXTNAJUR)
                            .addComponent(TXTTTL, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXTNAMA, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CBKOJUR, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(RBLK)
                                .addGap(18, 18, 18)
                                .addComponent(RBPR))
                            .addComponent(TXTNOPENDAFTARAN, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXTALAMAT))))
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(JJALUR, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(JBIAYAPENDAFTARAN, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(JPERHITUNGANBIAYA, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(JSPI)
                        .addComponent(JGELOMBANG)
                        .addComponent(JUKT))
                    .addComponent(JTOTALBIAYA, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TXTSPI)
                    .addComponent(TXTBIAYAPENDAFTARAN)
                    .addComponent(TXTUKT)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RBSNMPTN)
                                .addGap(18, 18, 18)
                                .addComponent(RBSBMPTN))
                            .addComponent(CBGELOMBANG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXTTOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(575, 575, 575))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(BTNDAFTAR)
                        .addGap(396, 396, 396)
                        .addComponent(BTNHITUNG))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(JFORM)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JFORM)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JNOPENDAFTARAN)
                    .addComponent(TXTNOPENDAFTARAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JJALUR)
                    .addComponent(RBSNMPTN)
                    .addComponent(RBSBMPTN))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JNAME)
                    .addComponent(TXTNAMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JSPI)
                    .addComponent(TXTSPI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTTL)
                    .addComponent(TXTTTL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JJENISKELAMIN)
                            .addComponent(RBLK)
                            .addComponent(RBPR)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JGELOMBANG)
                            .addComponent(CBGELOMBANG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JUKT)
                            .addComponent(TXTUKT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TXTALAMAT, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JALAMAT)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JBIAYAPENDAFTARAN)
                            .addComponent(TXTBIAYAPENDAFTARAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JAGAMA)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JKOJUR)
                    .addComponent(CBKOJUR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPERHITUNGANBIAYA)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTOTALBIAYA)
                    .addComponent(JNAJUR, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTNAJUR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTTOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNDAFTAR)
                    .addComponent(BTNKELUAR)
                    .addComponent(BTNHITUNG))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void CBKOJURItemStateChanged(java.awt.event.ItemEvent evt) {
}

private void TXTNAMAActionPerformed(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:
}

    private void CBKOJURActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBKOJURActionPerformed
if(CBKOJUR.getSelectedItem().equals("11"))
{TXTNAJUR.setText("Teknik Informatika");
TXTSPI.setText("20000000");
}

else
if(CBKOJUR.getSelectedItem().equals("12"))
{TXTNAJUR.setText("Teknik Komputer");
TXTSPI.setText("25000000");
}

else
if(CBKOJUR.getSelectedItem().equals("13"))
{TXTNAJUR.setText("Teknik Elektro");
TXTSPI.setText("15000000");
}

else
if(CBKOJUR.getSelectedItem().equals("14"))
{TXTNAJUR.setText("Teknik Sipil");
TXTSPI.setText("10000000");
}

else
if(CBKOJUR.getSelectedItem().equals("15"))
{TXTNAJUR.setText("Teknik Mesin");
TXTSPI.setText("20000000");
}

else
{TXTNAJUR.setText(null);
TXTSPI.setText(null);
}
    }//GEN-LAST:event_CBKOJURActionPerformed

    private void CBGELOMBANGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBGELOMBANGActionPerformed
        // TODO add your handling code here:
        if(CBGELOMBANG.getSelectedItem().equals("1"))
        {TXTBIAYAPENDAFTARAN.setText("200000");
}
        else
        if(CBGELOMBANG.getSelectedItem().equals("2"))
        {TXTBIAYAPENDAFTARAN.setText("300000");
}
        else
        {TXTBIAYAPENDAFTARAN.setText(null);
}
    }//GEN-LAST:event_CBGELOMBANGActionPerformed

    private void RBSNMPTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBSNMPTNActionPerformed
        // TODO add your handling code here:
        int biaya;
        biaya=0;
        TXTUKT.setText(String.valueOf(biaya));
    }//GEN-LAST:event_RBSNMPTNActionPerformed

    private void RBSBMPTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBSBMPTNActionPerformed
        // TODO add your handling code here:
        int biaya;
        biaya=7500000;
        TXTUKT.setText(String.valueOf(biaya));
    }//GEN-LAST:event_RBSBMPTNActionPerformed

    private void BTNDAFTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNDAFTARActionPerformed
if(TXTNAMA.getText().equals("")||TXTNOPENDAFTARAN.getText().equals("")||TXTTTL.getText().equals("")||TXTALAMAT.getText().equals("")
        ||TXTNAJUR.getText().equals("")||TXTSPI.getText().equals("")||TXTUKT.getText().equals("")||TXTBIAYAPENDAFTARAN.getText().equals(""))
{
JOptionPane.showMessageDialog(null, "Data Tidak Boleh Kosong !","Kesalahan", JOptionPane.ERROR_MESSAGE);
}
else{
        JOptionPane.showMessageDialog(null,"selamat anda telah terdaftar");}
    }//GEN-LAST:event_BTNDAFTARActionPerformed

    private void BTNKELUARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNKELUARActionPerformed
System.exit(0);
    }//GEN-LAST:event_BTNKELUARActionPerformed

    private void BTNHITUNGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNHITUNGActionPerformed
double totalbiaya,pendaftaran,spi,ukt;
pendaftaran=Double.parseDouble(TXTBIAYAPENDAFTARAN.getText());
spi=Double.parseDouble(TXTSPI.getText());
ukt=Double.parseDouble(TXTUKT.getText());
totalbiaya=pendaftaran+spi+ukt;
TXTTOTAL.setText(String.valueOf(totalbiaya));
    }//GEN-LAST:event_BTNHITUNGActionPerformed


    /**
     *
     * @param args  the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


try {

for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {

if ("Nimbus".equals(info.getName())) {

javax.swing.UIManager.setLookAndFeel(info.getClassName());

break;

}

}

} catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {

java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

}
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNDAFTAR;
    private javax.swing.JButton BTNHITUNG;
    private javax.swing.JButton BTNKELUAR;
    private javax.swing.JComboBox<String> CBGELOMBANG;
    private javax.swing.JComboBox<String> CBKOJUR;
    private javax.swing.JLabel JAGAMA;
    private javax.swing.JLabel JALAMAT;
    private javax.swing.JLabel JBIAYAPENDAFTARAN;
    private javax.swing.JLabel JFORM;
    private javax.swing.JLabel JGELOMBANG;
    private javax.swing.JLabel JJALUR;
    private javax.swing.JLabel JJENISKELAMIN;
    private javax.swing.JLabel JKOJUR;
    private javax.swing.JLabel JNAJUR;
    private javax.swing.JLabel JNAME;
    private javax.swing.JLabel JNOPENDAFTARAN;
    private javax.swing.JLabel JPERHITUNGANBIAYA;
    private javax.swing.JLabel JSPI;
    private javax.swing.JLabel JTOTALBIAYA;
    private javax.swing.JLabel JTTL;
    private javax.swing.JLabel JUKT;
    private javax.swing.JRadioButton RBLK;
    private javax.swing.JRadioButton RBPR;
    private javax.swing.JRadioButton RBSBMPTN;
    private javax.swing.JRadioButton RBSNMPTN;
    private javax.swing.JTextField TXTALAMAT;
    private javax.swing.JTextField TXTBIAYAPENDAFTARAN;
    private javax.swing.JTextField TXTNAJUR;
    private javax.swing.JTextField TXTNAMA;
    private javax.swing.JTextField TXTNOPENDAFTARAN;
    private javax.swing.JTextField TXTSPI;
    private javax.swing.JTextField TXTTOTAL;
    private javax.swing.JTextField TXTTTL;
    private javax.swing.JTextField TXTUKT;
    private javax.swing.JComboBox<String> jComboBox1;
    // End of variables declaration//GEN-END:variables
}